version: '3.9'

services:

  sops_enc:
    build:
      context: .
      dockerfile: ./encryption/dockerfile
    tty: true

  sops_des:
    build:
      context: .
      dockerfile: ./desencryption/dockerfile
    tty: true
