version: '3.9'

services:

  sops_enc:
    build:
      context: .
      dockerfile: ./encription/dockerfile
    tty: true

  sops_des:
    build:
      context: .
      dockerfile: ./desencription/dockerfile
    tty: true
